version: "3.8"

# volumes:
#   mymymyVol:

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: bind
        source: C:/Projects/Spielwiese/BMonkey/db/mysql
        target: /var/lib/mysql
    networks: 
      - bmonkey-net
      # - type: volume
      #   source: mymymyVol

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - bmonkey-net
networks:
  bmonkey-net:
    driver: "bridge"